# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_deleter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='goods')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('click', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subtitle', models.CharField(max_length=200)),
                ('kucun', models.IntegerField(default=100)),
                ('content', tinymce.models.HTMLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodCategory')),
            ],
        ),
    ]
