# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170707_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='is_deleter',
            new_name='is_deleted',
        ),
    ]
