# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercenter', '0002_auto_20170705_1933'),
        ('goods', '0004_pictest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.TTSXUser')),
            ],
        ),
    ]
