# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170711_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
